# 微信公众号和小红书配置示例
# 复制以下配置到你的 _config.yml 文件中

author:
  # ... 其他配置 ...

  # 微信公众号配置
  wechat_mp: "BlackSun_HCI" # 你的微信公众号ID或名称
  wechat_qr_image: "images/wechat_qr.png" # 二维码图片路径

  # 小红书配置
  rednote: "black_sun_hci" # 你的小红书用户名


  # ... 其他配置 ...
# 使用说明：
# 1. wechat_mp: 填写你的微信公众号ID或名称
# 2. wechat_qr_image: 将你的微信公众号二维码图片放在 images/ 目录下，然后在这里指定路径
# 3. rednote: 填写你的小红书用户名，系统会自动生成链接到你的小红书主页
# 4. 保存配置文件后重启 Jekyll 服务器
# 5. 在侧边栏中会显示新的社交媒体链接

# 新功能：
# - 点击微信公众号链接会直接显示二维码，不会弹出空白页面
# - 二维码提示使用英文显示
# - 支持点击背景关闭二维码模态框
# - 微信公众号图标使用微信绿色 (#07C160)
# - 小红书图标使用小红书红色 (#FF2442)
# - 悬停时有颜色变化效果
